export const countries: {
  label: string;
  value: string;
  optionProps?: React.OptionHTMLAttributes<HTMLOptionElement>;
}[] = [
  { label: "Aruba", value: "ABW" },
  { label: "Afghanistan", value: "AFG" },
  { label: "Angola", value: "AGO" },
  { label: "Anguilla", value: "AIA" },
  { label: "Åland Islands", value: "ALA" },
  { label: "Albania", value: "ALB" },
  { label: "Andorra", value: "AND" },
  { label: "United Arab Emirates", value: "ARE" },
  { label: "Argentina", value: "ARG" },
  { label: "Armenia", value: "ARM" },
  { label: "American Samoa", value: "ASM" },
  { label: "Antarctica", value: "ATA" },
  {
    label: "French Southern Territories",
    value: "ATF",
  },
  { label: "Antigua and Barbuda", value: "ATG" },
  { label: "Australia", value: "AUS" },
  { label: "Austria", value: "AUT" },
  { label: "Azerbaijan", value: "AZE" },
  { label: "Burundi", value: "BDI" },
  { label: "Belgium", value: "BEL" },
  { label: "Benin", value: "BEN" },
  {
    label: "Bonaire, Sint Eustatius and Saba",
    value: "BES",
  },
  { label: "Burkina Faso", value: "BFA" },
  { label: "Bangladesh", value: "BGD" },
  { label: "Bulgaria", value: "BGR" },
  { label: "Bahrain", value: "BHR" },
  { label: "Bahamas", value: "BHS" },
  { label: "Bosnia and Herzegovina", value: "BIH" },
  { label: "Saint Barthélemy", value: "BLM" },
  { label: "Belarus", value: "BLR" },
  { label: "Belize", value: "BLZ" },
  { label: "Bermuda", value: "BMU" },
  {
    label: "Bolivia, Plurinational State of",
    value: "BOL",
  },
  { label: "Brazil", value: "BRA" },
  { label: "Barbados", value: "BRB" },
  { label: "Brunei Darussalam", value: "BRN" },
  { label: "Bhutan", value: "BTN" },
  { label: "Bouvet Island", value: "BVT" },
  { label: "Botswana", value: "BWA" },
  { label: "Central African Republic", value: "CAF" },
  { label: "Canada", value: "CAN" },
  { label: "Cocos (Keeling) Islands", value: "CCK" },
  { label: "Switzerland", value: "CHE" },
  { label: "Chile", value: "CHL" },
  { label: "China", value: "CHN" },
  { label: "Côte d'Ivoire", value: "CIV" },
  { label: "Cameroon", value: "CMR" },
  {
    label: "Congo, Democratic Republic of the",
    value: "COD",
  },
  { label: "Congo", value: "COG" },
  { label: "Cook Islands", value: "COK" },
  { label: "Colombia", value: "COL" },
  { label: "Comoros", value: "COM" },
  { label: "Cabo Verde", value: "CPV" },
  { label: "Costa Rica", value: "CRI" },
  { label: "Cuba", value: "CUB" },
  { label: "Curaçao", value: "CUW" },
  { label: "Christmas Island", value: "CXR" },
  { label: "Cayman Islands", value: "CYM" },
  { label: "Cyprus", value: "CYP" },
  { label: "Czechia", value: "CZE" },
  { label: "Germany", value: "DEU" },
  { label: "Djibouti", value: "DJI" },
  { label: "Dominica", value: "DMA" },
  { label: "Denmark", value: "DNK" },
  { label: "Dominican Republic", value: "DOM" },
  { label: "Algeria", value: "DZA" },
  { label: "Ecuador", value: "ECU" },
  { label: "Egypt", value: "EGY" },
  { label: "Eritrea", value: "ERI" },
  { label: "Western Sahara", value: "ESH" },
  { label: "Spain", value: "ESP" },
  { label: "Estonia", value: "EST" },
  { label: "Ethiopia", value: "ETH" },
  { label: "Finland", value: "FIN" },
  { label: "Fiji", value: "FJI" },
  {
    label: "Falkland Islands (Malvinas)",
    value: "FLK",
  },
  { label: "France", value: "FRA" },
  { label: "Faroe Islands", value: "FRO" },
  {
    label: "Micronesia, Federated States of",
    value: "FSM",
  },
  { label: "Gabon", value: "GAB" },
  { label: "United Kingdom", value: "GBR" },
  { label: "Georgia", value: "GEO" },
  { label: "Guernsey", value: "GGY" },
  { label: "Ghana", value: "GHA" },
  { label: "Gibraltar", value: "GIB" },
  { label: "Guinea", value: "GIN" },
  { label: "Guadeloupe", value: "GLP" },
  { label: "Gambia", value: "GMB" },
  { label: "Guinea-Bissau", value: "GNB" },
  { label: "Equatorial Guinea", value: "GNQ" },
  { label: "Greece", value: "GRC" },
  { label: "Grenada", value: "GRD" },
  { label: "Greenland", value: "GRL" },
  { label: "Guatemala", value: "GTM" },
  { label: "French Guiana", value: "GUF" },
  { label: "Guam", value: "GUM" },
  { label: "Guyana", value: "GUY" },
  { label: "Hong Kong", value: "HKG" },
  { label: "Honduras", value: "HND" },
  { label: "Croatia", value: "HRV" },
  { label: "Haiti", value: "HTI" },
  { label: "Hungary", value: "HUN" },
  { label: "Indonesia", value: "IDN" },
  { label: "India", value: "IND" },
  { label: "Ireland", value: "IRL" },
  { label: "Iran", value: "IRN" },
  { label: "Iraq", value: "IRQ" },
  { label: "Iceland", value: "ISL" },
  { label: "Israel", value: "ISR" },
  { label: "Italy", value: "ITA" },
  { label: "Jamaica", value: "JAM" },
  { label: "Japan", value: "JPN" },
  { label: "Kazakhstan", value: "KAZ" },
  { label: "Kenya", value: "KEN" },
  { label: "Kyrgyzstan", value: "KGZ" },
  { label: "Cambodia", value: "KHM" },
  { label: "Kiribati", value: "KIR" },
  { label: "South Korea", value: "KOR" },
  { label: "Kuwait", value: "KWT" },
  { label: "Malaysia", value: "MYS" },
  { label: "Mexico", value: "MEX" },
  { label: "Netherlands", value: "NLD" },
  { label: "Norway", value: "NOR" },
  { label: "Philippines", value: "PHL" },
  { label: "United States of America", value: "USA" },
  { label: "Vietnam", value: "VNM" },
  { label: "Zimbabwe", value: "ZWE" },
];
